image:
  name: hashicorp/terraform
  entrypoint:
    - /usr/bin/env


before_script:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION="us-west-2"

stages:
  - package
  - plan
  - apply
  - destroy
  - deploy

package:
  stage: package
  image: registry.gitlab.com/who-docker/aws-cli:latest
  script:
      - cd lambda
      - zip ../hello.zip main.js
      - aws s3 cp ../hello.zip s3://2020-terraform-demo/v1.0.0/hello.zip
  only:
    - master

plan:
  stage: plan
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform plan -out out.tfplan
    - terraform show -json out.tfplan > tfplan.json
  artifacts:
    expire_in: 8 weeks
    paths:
      - terraform/out.tfplan
      - terraform/tfplan.json
  only:
    - master

apply:
  stage: apply
  script:
      - cd terraform
      - echo $tfc_credentials > /root/.terraformrc
      - terraform init
      - terraform apply -input=false out.tfplan
  only:
    - master

destroy:
  stage: destroy
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - master
    