image:
  name: hashicorp/terraform
  entrypoint:
    - /usr/bin/env


before_script:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION="us-west-2"
  - export AWS_DEFAULT_ROLE="demo_terraform_2020"

stages:
  - package
  - plan
  - apply
  - destroy

package:
  stage: package
  image: registry.gitlab.com/who-docker/aws-cli:latest
  script:
      - cd lambda
      - zip ../hello.zip main.js
      - aws s3 cp ../hello.zip s3://2020-terraform-demo/v1.0.0/hello.zip
  only:
    - complete

plan:
  stage: plan
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform plan -var-file="./variables.tfvars" -out out.tfplan
    - terraform show -json out.tfplan > tfplan.json
  artifacts:
    expire_in: 8 weeks
    paths:
      - terraform/out.tfplan
      - terraform/tfplan.json
  only:
    - complete

apply:
  stage: apply
  script:
      - cd terraform
      - echo $tfc_credentials > /root/.terraformrc
      - terraform init
      - terraform apply -var-file="./variables.tfvars" -input=false -state=state.tfstate out.tfplan
  artifacts:
    expire_in: 8 weeks
    paths:
      - terraform/state.tfstate
  only:
    - complete

destroy:
  stage: destroy
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform destroy -state=state.tfstate -auto-approve
  when: manual
  only:
    - complete

onFail:
  stage: destroy
  image: registry.gitlab.com/who-docker/aws-cli:latest
  script: 
    - aws iam delete-role --role-name $AWS_DEFAULT_ROLE
  when: on_failure
  only:
    - complete

    